<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
    </style>
</head>
<body>
<img src="https://i.imgur.com/IS8PvsV.png" alt="">
<h2><a href="http://localhost:8080/confirm/${confirm_code}">Для завершения пройдите по ссылке</a></h2>
</body>
</html>
